version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: pera-invest-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
      - ./docker-volumes/mysql-conf:/etc/mysql/conf.d
      - ./Sql:/docker-entrypoint-initdb.d